plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0-SNAPSHOT'
description = 'MyMavenToGradle'

sourceCompatibility = 11
targetCompatibility = 11

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:3.8.1'
}

application {
    mainClassName = 'com.example.App' // Compatible with older Gradle versions
}

jar {
    manifest {
        attributes(
            'Main-Class': 'com.example.App'
        )
    }
}
